spring.data.mongodb.auto-index-creation=true
spring.application.name=backend
spring.mongodb.uri=mongodb://localhost:27017/deepsights_db
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
server.port=8086
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.chat.memory.repository.mongo.create-indices=false